openapi: 3.0.3

info:
  title: TD Final Part 1
  description: TD Final Part 1
  version: 1.0.0

servers:
  - url: 'http://localhost:8080'
paths:
  /Competition:
    get:
      tags:
        - Competition
      summary: Get all competition
      operationId: getAllCompetition
      responses:
        200:
          description: List of competition
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'
    post:
      tags:
        - Competition
      summary: create competition
      operationId: createCompetition
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateCompetition'
      responses:
        '200':
          description: A list of competition
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'
  /Player:
    get:
      tags:
        - Player
      summary: Get all player
      operationId: getAllPlayer
      responses:
        200:
          description: List of player
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
    post:
      tags:
        - Player
      summary: create player
      operationId: createPlayer
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreatePlayer'
      responses:
        '200':
          description: A list of player
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'
  /Team:
    get:
      tags:
        - Team
      summary: Get all team
      operationId: getAllTeam
      responses:
        200:
          description: List of team
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
    post:
      tags:
        - Team
      summary: create team
      operationId: createTeam
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateTeam'
      responses:
        '200':
          description: A list of team
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
components:
  schemas:
    Competition:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateCompetition'
    CreateCompetition:
      properties:
        id:
          type: string
        name:
          type: string
        country:
          type: string
    Player:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreatePlayer'
    CreatePlayer:
      type: object
      properties:
        name:
          type: string
        number:
          type: integer
        strongFoot:
          type: string
    Team:
      type: object
      properties:
        ListCompetition:
          type: array
          items:
            $ref: '#/components/schemas/Competition'
        ListPlayer:
          type: array
          items:
            $ref: '#/components/schemas/Player'
      allOf:
        - $ref: '#/components/schemas/CreateTeam'
    CreateTeam:
      properties:
        name:
          type: string
        slogan:
          type: string